In [2]:
## 入门

import torch

# 生成tensor
x = torch.arange(12)    # 生成element从0~11的一维tensor
x1 = torch.arange((12)) # 和上面写法等价

print(x)
print(x1)

# 其他一些写法，zeros是全零，ones是全一，randn是标准高斯分布
x2 = torch.zeros(2,3,4)  # 也可以写成 torch.zeros((2,3,4))
print(x2)

x3 = torch.ones((2,3,4))
x4 = torch.randn(2,3,4)

print(x3)
print(x4)

print(x4.shape)    # 返回torch.Size([2,3,4])
print(x4.shape[0]) # 返回torch.Size([2,3,4])的第一维的值，也就是2
print(x4.numel())  # 返回元素个数，也就是2*3*4=24

x5 = x4.reshape(4,6)
x6 = x4.reshape(4, -1)  # 用-1 代表自动计算...

print(x5)
print(x6)

# 最后，tensor也可以手工指定
x7 = torch.tensor([[1,2,3],[1,2,3]]) # 手工指定(2,3)的二维矩阵
print(x7.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[[-1.2911, -1.8431,  0.7995, -0.1826],
         [ 0.5918,  1.1331, -0.9081, -1.1502],
         [ 0.5723, -0.7427,  1.4737,  1.0406]],

        [[ 0.1881, -0.6787,  0.3107, -0.7220],
         [-0.9186,  0.0493,  0.6530,  0.1796],
         [ 0.8669, -1.3810, -0.7984,  1.3388]]])
torch.Size([2, 3, 4])
2
24
tensor([[-1.2911, -1.8431,  0.7995, -0.1826,  0.5918,  1.1331],
        [-0.9081, -1.1502,  0.5723, -0.7427,  1.4737,  1.0406],
        [ 0.1881, -0.6787,  0.3107, -0.7220, -0.9186,  0.0493],
        [ 0.6530,  0.1796,  0.8669, -1.3810, -0.7

In [3]:
## 运算符

Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))# 按位计算，只要形状相同就行
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算, 这些运算是按元素，也就是element-wise

torch.exp(x)  # 按位进行 exp运算

# concatenate 连结操作
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print(X.shape)
print(Y.shape)

# 在维度1进行连结，连结后维度1的值为X,Y维度1的值的和，其余维度不变(X,Y剩余维度应该相等)
# 这里，第一维即dim=0，结果是3+3=6，第二维dim=1，不变，还是4
a0 = torch.cat((X, Y), dim=0)  

# 这里，第一维即dim=0，结果不变是3，第二维dim=1，4+4=8
a1 = torch.cat((X, Y), dim=1)

print(a0.shape)  # 应该是torch.Size([6, 4])
print(a1.shape)  # 应该是torch.Size([3, 8])

# 对 == 操作，也是按元素，只不过对应位置元素相同为True，否则为False
a = (x==y)
print(a)   # tensor([False,  True, False, False])
print(a[1])

# 对所有元素求和，得到一个单元素张量
print(X.sum())  # tensor(66.), 即0~12的和


torch.Size([3, 4])
torch.Size([3, 4])
torch.Size([6, 4])
torch.Size([3, 8])
tensor([False,  True, False, False])
tensor(True)
tensor(66.)


In [4]:
## 广播机制
# 核心就是如何在形状不相同的两个张量上执行按元素操作，机制如下
# 1. 通过适当复制元素来扩展一个或两个数组，以便在转换之后，两个张量具有相同的形状；
# 2. 对生成的数组执行按元素操作。

# 在大多数情况下，我们将沿着数组中长度为1的轴进行广播
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))

# 为了让a和b能按元素操作，将(3,1)的a和(1,2)的b，都变成(3,2),此时a复制列，b复制行
# a 从[[0],[1],[2]]变为[[0,0],[1,1],[2,2]]
# b 从[0,1]变为[[0,1],[0,1],[0,1]]
c = a + b
print(c)
print(c.shape)

d = a * b
print(d)
print(d.shape)

tensor([[0, 1],
        [1, 2],
        [2, 3]])
torch.Size([3, 2])
tensor([[0, 0],
        [0, 1],
        [0, 2]])
torch.Size([3, 2])


In [9]:
## 索引和切片

x = torch.arange(12)
print(x[-1])  # 通过下标访问

y = x.reshape(-1, 4)
print(y)
print(y[1,3])  # 多维张量也可以通过下标访问
y[1,1] = 9     # 通过下标赋值

# "0:2"说明第一维要访问第1第2行， “:”说明要访问所有列(沿轴1的所有列)，12就是为所有元素赋值
# liujia: 实际上，我感觉 : 代表了后面的所有维度的所有元素
y[0:2, :] = 12    # 隐式用了广播机制 
print(y[0:2, :])  # 

tensor(11)
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor(7)
tensor([[12, 12, 12, 12],
        [12, 12, 12, 12]])


In [11]:
## 节省内存

X = torch.tensor([1, 2])
Y = torch.tensor([2, 3])
print(id(Y))
Y = Y + X
print(id(Y))   # Y的地址变了，总的来说，Y=Y+X 是先计算Y+X，然后为结果分配内存，最后使Y指向新内存

# 要节省内存，就要使用"原地操作"
# 我们可以使用切片表示法将操作的结果分配给先前分配的数组，例如Y[:] = <expression>
Z = torch.zeros_like(Y)  # Z的形状如同Y, 但值为0
print('id(Z):', id(Z))
Z[:] = X + Y             # : 和上面的注释一样，表明了所有维度的所有元素，用 X+Y的对应的element赋值
print('id(Z):', id(Z))



126693885409328
126694087194592


In [12]:
## 转换为其他python对象，主要是转numpy

A = X.numpy()        # 转为numpy的ndarray对象
print(type(A))

B = torch.tensor(A)  # 类似强制类型转换那样，将ndarray转为tensor
print(type(B))

a = torch.tensor([2.5])
print(a)
print(a.item())   # item()将大小为1的张量转为python的标量
print(float(a))
print(int(a))




<class 'numpy.ndarray'>
<class 'torch.Tensor'>
tensor([2.5000])
2.5
2.5
2
